[package]
name = "rust-flac-meta-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
flac = "0.5.0"
walkdir = "2.3.2"
